theme: jekyll-theme-minimal
title: Resume
description: Zainab Obaid's Resume
linkedin_public_url: https://www.linkedin.com/in/zainab-obaid/
me-img: "/zazee.jpg"
logo: "/zazee.jpg"
email: zainababdobaid@gmail.com
