theme: jekyll-theme-minimal
title: Resume
description: Zainab Obaid's Resume
linkedin_public_url: https://www.linkedin.com/in/zainab-obaid/
logo: "https://github.com/zainabobaid/resume/blob/gh-pages/zazee.jpg"
